// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingAppAPI.Models;

namespace ParkingAppAPI.Migrations
{
    [DbContext(typeof(SlotContext))]
    [Migration("20191017103751_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingAppAPI.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("posX")
                        .HasColumnType("int");

                    b.Property<int>("posY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("slots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4f2801b-9c02-42ab-9c79-d1e0e6833d3b"),
                            IsOccupied = true,
                            posX = 0,
                            posY = 1
                        },
                        new
                        {
                            Id = new Guid("fde8d12a-1d6e-43eb-8a00-7bdda7c8c84b"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 2
                        },
                        new
                        {
                            Id = new Guid("cc823fca-9054-4cd2-828a-40348834ec6e"),
                            IsOccupied = true,
                            posX = 0,
                            posY = 3
                        },
                        new
                        {
                            Id = new Guid("c37e227b-7487-427a-8dc5-004d8ac45352"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
