// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingApp.API.Models;

namespace ParkingApp.API.Migrations
{
    [DbContext(typeof(SlotContext))]
    [Migration("20191021074528_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingApp.API.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("posX")
                        .HasColumnType("int");

                    b.Property<int>("posY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("slots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a6964b5-12f5-45c4-9b51-c619642815cd"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 0
                        },
                        new
                        {
                            Id = new Guid("f31bf444-0966-4580-84cf-36823400e0de"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 1
                        },
                        new
                        {
                            Id = new Guid("d84ed0c3-8fe5-4b0a-ad71-f4551830ccbf"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 2
                        },
                        new
                        {
                            Id = new Guid("38693933-1c78-4a65-9e46-06cc258a4194"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 3
                        },
                        new
                        {
                            Id = new Guid("a89afa90-88c2-440d-a84e-bbce6d8a203a"),
                            IsOccupied = false,
                            posX = 0,
                            posY = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
